### ISSUE TITLE
Allow target rate hours to be set from another entity

### ISSUE THREAD

**Issue by agentgonzo** [BottlecapDave/HomeAssistant-OctopusEnergy#1013]
### Describe the feature

At present, when setting up a target rate, you enter in the number of hours as a decimal. 

It would be handy to allow this to come form and other number entity, rather than a fixed value

### Expected behaviour

The hours to charge for a target rate can be set from another entity

### Use Case

Depending on the expected solar generation (Solcast)  and the current battery level, the amount of time I want to charge the battery will vary. 

Setting up another helper entity to calculate how much extra I need to charge the battery from the grid is easy. I'd then like the charging window to be calculated based on this dynamic value rather than a fixed one. 

Thanks!

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello and thanks for the feature request. As per the [docs](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/services/#octopus_energyupdate_target_config), this functionality is currently exposed via a service. You can use this service as part of an automation, or if you're wanting to expose this via an input senor, then you can have an automation that listens for changes on the input sensor and updates via the service accordingly. This service doesn't currently persist the changes between restarts, but it's on the list to [investigate this functionality](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/1014) in the future (please follow and upvote for updates).

Because of this, and because it would need to be all settings exposed via sensors (where it's difficult to sync data between different sensors) not just this one I have no plans on proceeding with this request.

**Comment by agentgonzo** [comment]
That's great! Thanks.

**Comment by agentgonzo** [comment]
Thanks @BottlecapDave - I'm just trying it... but the service only seems to allow setting it from a fixed string:
![image](https://github.com/user-attachments/assets/9fa083da-92da-4b28-81ff-5d2bedf68fe3)

If I try to edit it in the yaml editor and use a template, it complains that the it's expecting a string and I'm not passing a string.
```
alias: test script
sequence:
  - variables:
      hours: "1.0"
  - service: octopus_energy.update_target_config
    data:
      target_hours: {{ hours }}
    target:
      entity_id: binary_sensor.octopus_energy_target_agile_charging
description: ""
fields: {}

```

> Failed to call service script/test_script. expected str for dictionary value @ data['target_hours']

**Comment by DaveK-Rocketmakers** [comment]
I haven't had a chance to try your specific example, but the docs have an automation example below the service definition for updating the config from input helpers. I believe you need to put single quotes around your target hours

```
target_hours: '{{ hours }}'
```

**Comment by BottlecapDave** [comment]
I haven't had a chance to try your specific example, but the docs have an automation example below the service definition for updating the config from input helpers. I believe you need to put single quotes around your target hours

```
target_hours: '{{ hours }}'
```

**Comment by agentgonzo** [comment]
I've tried it every way. Single quotes, double quotes. Quotes around the double braces, quotes within the double braces. quotes around the hours, both double, and single. I cant' get it to work.

AAaaahhh! I finally got it to work. It needs to be put in a newline.
eg:
Working
```
      target_hours: >
        "{{ hours | string }}"
```

NOT woring:
```
      target_hours: "{{ hours | string }}"
```
