### ISSUE TITLE
API Test Script

### ISSUE THREAD

**Issue by psfshr** [BottlecapDave/HomeAssistant-OctopusEnergy#1065]
### Describe the feature

To have a separate (not part of the integration) test script (e.g. in Python), which we can run outside of HA to check OE API connectivity. E.g. when run, it performs the same basic set of queries that the integration does and reports on whether there's any issues retrieving data.

### Expected behaviour

Script is downloaded, and edited to include OE API & account info. When the script is run it connects to the OE API in the same way as the integration and performs a set of queries in the same way as the integration does. Each query is reported with a Success/Fail along with any appropriate results and/or error details.

### Use Case

To provide a method to test API access outside of the integration and HA. When there's issues with OE API connectivity it can be difficult sometimes to tell whether it's an issue with OE, HA, or the API, and this would help troubleshoot those issues.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello and thanks for the feature request. Currently the [diagnostics](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq/#ive-been-asked-for-my-meter-information-in-a-bug-request-how-do-i-obtain-this) runs the API client functions independently and return a high level view of the results from the API (e.g. the last date available for previous electricity consumption). This does include one fallback around account information where it uses the cached data if the up-to-date information can't be obtained. There are also the integration tests which call the various endpoints (which are supported by my account). Because of these, I have no plans to add any additional tooling as I feel these match your requirements already.
