### ISSUE TITLE
Integration is unavailable more and more frequently

### ISSUE THREAD

**Issue by jacoscar** [BottlecapDave/HomeAssistant-OctopusEnergy#1067]
### Describe the bug

I'm getting this very often recently
![image](https://github.com/user-attachments/assets/9415ca06-0a69-4ba8-a40e-711a8a017689)

### Reproduction steps

n/a

### Expected behaviour

n/a

### Tariff Code

 E-1R-INTELLI-VAR-22-10-14-B

### Integration Version

12.2.1

### Home Assistant Version

2024.8.3

### Fresh Install?

Not specified

### Home Assistant Logs

This error originated from a custom integration.

Logger: custom_components.octopus_energy.coordinators.current_consumption
Source: custom_components/octopus_energy/coordinators/current_consumption.py:55
integration: Octopus Energy (documentation, issues)
First occurred: October 31, 2024 at 10:32:21 PM (267 occurrences)
Last logged: 11:45:30 AM

Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-11-08 11:39:17.987932+00:00
Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-11-08 11:44:42.987498+00:00
Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-11-08 11:44:49.866671+00:00
Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-11-08 11:46:42.987498+00:00
Failed to retrieve smart meter consumption data - using cached version. Next attempt at 2024-11-08 11:46:49.866671+00:00

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry to hear you're having issues. 

The first thing I would suggest is update the integration, as you're a few versions behind. 

Secondly, the screenshot you provided looks like a different integration (ha_octopus_intelligent?). By using multiple integrations with your OE account, you run the risk of hitting rate limiting which might be causing you issues. This integration provides everything that integration provides plus a little more. There's a guide on how each entity translates - https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/entities/intelligent/#migrating-from-megakidha_octopus_intelligent. Alternatively, you can disable all intelligent related entities provided by this integration and this integration will not request the related data which might ease on the request limits.

Thirdly, those warnings are normal. The OE APIs can be flakey at times and there's very little I can do being a cloud based integration. I fall back onto cached data where available in these situations. Again, this might be caused by you using multiple OE based integrations.

**Comment by jacoscar** [comment]
Thanks, I see what I've done; I installed the two integrations at different times and then forgot they are separate. I have now removed Octopus Intelligent and I'll see how I get on!

**Comment by BottlecapDave** [comment]
Do you have any errors in your logs in relation to the integration?

**Comment by mt104** [comment]
I see lots of timeouts. Here's one that doesn't show any meter numbers etc...
![image](https://github.com/user-attachments/assets/63e4c8f7-a769-47af-942b-2df32b110e51)

**Comment by rwfnf** [comment]
I'm getting a lot of these similar timeout errors on version 13.1.0 lately. Did Octopus change the limits or something? How can I check how often the API is being called?

<img width="978" alt="Screenshot 2024-11-08 at 18 05 22" src="https://github.com/user-attachments/assets/2830672a-a159-4fa4-8bbf-d9d930372e5e">
<img width="807" alt="Screenshot 2024-11-08 at 18 04 54" src="https://github.com/user-attachments/assets/85ae68b8-9293-43bd-bce2-98a310f1fa70">
<img width="902" alt="Screenshot 2024-11-08 at 18 04 40" src="https://github.com/user-attachments/assets/9aa9c360-5211-43d6-b083-0af49e0e29fb">

**Comment by BottlecapDave** [comment]
My guess is there API is having a moment and dropping connections. It unfortunately happens from time to time. If I increase the timeout too much then the background jobs that fetch the data will start tripping over themselves. The only thing I can do in this situation is use the cached data. The fact it doesn't happen all of the time without people touching the integration and being on various versions means it's highly likely it's OE end.

**Comment by BottlecapDave** [comment]
It looks like the integration is getting throttled for some reason. v13.1.1 is an attempt at getting around this throttling, but it may come back. I've reached out of OE to try and find out why the integration is getting throttled.
