### ISSUE TITLE
Usage shown at 8am today.

### ISSUE THREAD

**Issue by garethsnaim** [BottlecapDave/HomeAssistant-OctopusEnergy#107]
**Describe the bug**

Hello, and thank you for this great integration. Forgive me I am still learning however in the 'energy' section of HA, I have I believe set up Octupus with electric and gas. However after a day I only have one reading that says accumulative, which I think could be for yesterday. But in the graph its listed under today at 8am? Is this perhaps because thats when the data was released?

Also it has not pulled any historical data, is that to be expected?

Thanks for your help

**To Reproduce**

**Expected behavior**

On Hugo app for instance which is using same API, it pulled historical data for last year, was hopeful woul dbe the case here but no big deal if its not

**Home Assistant Version**

2022.12.4

**Integration Version**

4.7.1

**Fresh Install?**

Brand new

**Home Assistant Logs**

Are there any related logs available in Home Assistant? It is suggested you set your [log level](https://www.home-assistant.io/integrations/logger/) to `debug` and then check the "Full Home Assistant Log" from the `logs page`.

**Comment by BottlecapDave** [comment]
Hello and sorry for the late response.

As per the [readme](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy#can-i-add-the-sensors-to-the-energy-dashboard), this is by design due to both a limitation with the data available by Octopus Energy (always a day behind) and Home Assistant (no documented way of adding data retrospectively into the energy dashboard). If this behaviour ever changes, you can be sure I'll be looking into it :)
