### ISSUE TITLE
No Free Electric Events Listed

### ISSUE THREAD

**Issue by leacho73** [BottlecapDave/HomeAssistant-OctopusEnergy#1092]
### Describe the bug

This morning we had a Free Electric session between 7am and 9am - I was expecting to see an event for this session, but none are listed.

### Reproduction steps

Unable to reproduce until next Free Electric session

### Expected behaviour

I expected an event to be created for the free session - such as event.octopus_energy_new_octoplus_free_electricity_session

### Tariff Code

E-1R-INTELLI-VAR-22-10-14-E

### Integration Version

13.1.3

### Home Assistant Version

2024.11.4

### Fresh Install?

After upgrading

### Home Assistant Logs

-

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by markfarringtonhome** [comment]
Our event here arrived at 7.12am and functioned as expected (bar the late start), I assumr octopus didn't have the data in the api until after the event, but we didn't see anything until during the event itself. Obviously if homeassistant is able to be aware of upcoming events in advance, it'd be useful for automations etc.

**Comment by BottlecapDave** [comment]
Hello and sorry for the inconvience. The Octopus Energy API doesn't provide an API for free electricity, so the data is supplied by a [personal API](https://github.com/BottlecapDave/OctopusEnergyApi/actions) that I have to update manually.

I unfortunately didn't see the event until 6am on sunday, which meant that users might not see the updated data until 7:30am at the latest (due to how often the integration polls the data).

I've added a few contingencies to try and make sure the event doesn't get missed again.

**Comment by markfarringtonhome** [comment]
In that case thanks for your excellent work as always!
