### ISSUE TITLE
Target rates not looking into the next day.

### ISSUE THREAD

**Issue by dmelliott20** [BottlecapDave/HomeAssistant-OctopusEnergy#123]
The target sensor appears to be not selecting rates that occur into the next day (post 12pm)

this only happens on the shorter targets (0.5 hours and 1 hours)
![95B1423F-685E-491A-9CEE-362D52505C5A](https://user-images.githubusercontent.com/13154453/212966821-81579fdf-3af5-4553-8cc8-3a80403678e8.png)

the longer targets (1.5hrs and over) work fine

![3E73B123-8717-47A6-B10B-8234CA9B2CEC](https://user-images.githubusercontent.com/13154453/212966946-9b6358ad-3788-4572-ad53-5240e2263071.png)

both sensors have start times of 22:00 and end times of 08:00

Thanks

**Comment by BottlecapDave** [comment]
Hi @dmelliott20, sorry to hear you're having issues. Some other users have reported similar issues in another thread. 

My testing indicates this shouldn't be happening, however I have some caching to only calculate rates if all previously calculated rates are in the past. I wonder if it's calculating it with only partial rates which is why when it turned over to midnight it re-calculated and turned on.

**Comment by dmelliott20** [comment]
No problem, thanks for your work on this add on.

If I can help testing in any way let me know. 

Dave

**Comment by BottlecapDave** [comment]
Hello. This should now be fixed within the latest release (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v5.3.0).

**Comment by dmelliott20** [comment]
Thanks Dave

Sent from my iPhone

On 20 Jan 2023, at 18:19, David Kendall ***@***.***> wrote:

﻿

Hello. This should now be fixed within the latest release (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v5.3.0).

**Comment by dmelliott20** [comment]
Confirm this looks resolved to me. Sensor worked fine last night.

**Comment by BottlecapDave** [comment]
Glad to hear :)
