### ISSUE TITLE
Log electricity usage per 30mins

### ISSUE THREAD

**Issue by retrodans** [BottlecapDave/HomeAssistant-OctopusEnergy#130]
**Describe the bug**

Sorry if this should be a feature, but I think it may be a bug. The integration appears to work nicely, I can see my rate change as expected (as on an eco7 tariff). 

But what doesn't appear right is that the consumption (both kW and gbp) are always the same in a 24hr window, as though it just checks a single time each day (looking in the database, maybe 2pm each day). 

**To Reproduce**

I have done very little, installed the app, waited until 24hrs, then looked at the data. 

**Expected behavior**

I was hoping to be able to see previous days usage broken down to deduce patterns of usage and high costs. 

**Home Assistant Version**

2023.1.6.

**Integration Version**

V5. 3.0

**Fresh Install?**

Fresh install

**Home Assistant Logs**

Are there any related logs available in Home Assistant? Please follow the instructions as outlined in the [readme](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy#increase-home-assistant-logs).

**Comment by BottlecapDave** [comment]
Hello. 

This is not currently possible for a number of reasons
* Octopus Energy data is only provided up to the previous day and doesn't provide live data (without their beta Octopus Home Mini). To my understanding, this is due to a limitation with smart meters.
* Home Assistant Energy Dashboard doesn't have a documented way of adding historic data. It only tracks live data.

These two reasons combined are why the previous sensor just has the combined value for the previous day, with the breakdowns available as an attribute. I came across a [forum post](https://community.home-assistant.io/t/octopus-energy-integration-display-graph-of-usage/484018) which details how you can use a plugin to show this data in graph form.

I'm also currently looking at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/121 to support breakdowns, but requires an additional device supplied by Octopus Energy. This will provide the data in hourly breakdowns (this seems to be the smallest value that Home Assistant exposes in the dashboard).

**Comment by retrodans** [comment]
Ah okay, thanks for the information, I have been using Octograph, but that allows adding historical data, which I think sounds like the main issue.  I will add myself to the mini waiting list too, as that looks tremendously interesting.
