### ISSUE TITLE
Octopus not updating previous rate before billing

### ISSUE THREAD

**Issue by th4rius** [BottlecapDave/HomeAssistant-OctopusEnergy#174]
Not sure if this a case for more people but I have noticed that Octopus doesn't seem to update daily export and sometimes usage of electricity and gas just before or around billing time. This results in missing stats and consumption records for few days.
I am wondering if there is a way to re-check the whole previous week and update or add those missing rates?

**Comment by BottlecapDave** [comment]
Hello and sorry that you're having issues.

Unfortunately, there isn't a way of checking previous weeks or adding missing rates due to the way the entity works, as it would change the context of the entity and provide invalid results with the energy dashboard.

Have you contacted OE directly on this matter?

**Comment by th4rius** [comment]
Yes I have but they said it is how it works. It is not perfect and there will be some lag in data being available for few days sometimes. Useless basically. Can't be just me having this lag. Are your tariffs updated everyday and never had a lag?

Also I think I have mentioned this before. I really appreciate your hard work but please please stop making constant changes to entities. They really screw up my long term stats and other automations. Last update the friendly names changed which added another entry in my fluxdb and the calculations are now all screwed up. I understand sometimes it is not possible but it would be good to stick to one convention.

Thanks

**Comment by BottlecapDave** [comment]
> Are your tariffs updated everyday and never had a lag

I personally can't say as I don't have any exports. I have had the occasional day where imports are missing because they haven't refreshed before midnight. I'm currently using the home mini which is giving me more accurate data, but I understand this is still in beta and not available for everyone. I'm not wanting to change the behaviour of the previous sensor as it's purpose is the previous day's worth of data and this could cause more confusion to existing and new users.

> Also I think I have mentioned this before. I really appreciate your hard work but please please stop making constant changes to entities. They really screw up my long term stats and other automations. Last update the friendly names changed which added another entry in my fluxdb and the calculations are now all screwed up. I understand sometimes it is not possible but it would be good to stick to one convention.

I've been careful for things that would break normal use of HA like entity ids in automations. As previously mentioned I don't take these changes lightly, but some are required as more people use the integration, more questions are raised and more things are shown as not to be obvious. For things like entity names, I did not raise this as a breaking change as they shouldn't break normal HA use (automations and dashboards should be based on ids not names). I'd be interested in why you are using the name and not id for your statistics as I would not consider the name to be stable in any use. To avoid future issues, you could manually set the name of the entities which should be used by HA over any default names.

**Comment by th4rius** [comment]
I'm using IDs. For HA it doesn't affect much. In this case I'm using influxdb for long term stats. Influx creates entries that you can filter down certain measurements. In this case it created another name into which it started collecting data. The old one then stopped collecting. So had to rename the entities back to old name so it can collect under old name. Hope that makes sense. Anyway I have managed to resolve this just it would have been annoying if I didn't notice for a long time.
