### ISSUE TITLE
Tracker Tariff - Rates suddenly 'unknown' until reload

### ISSUE THREAD

**Issue by realroywalker** [BottlecapDave/HomeAssistant-OctopusEnergy#216]
Firstly thanks for the great integration - it's so nice getting the Octopus data in HA!

I've been using it with Octopus Tracker Tariff and noticed recently that some of the entities (electricity current_rate, next_rate and previous_rate) randomly go 'unknown' in home assistant.
What is strange is if I go to integrations and tell the Octopus integration to reload they all populate again with the correct data.

I'm using the latest HACS release for the integration of 6.6.1 - if you need any further info please let me know.

**Comment by BottlecapDave** [comment]
Sorry to hear you're having intermittent issues. The tracker tariffs are not officially supported in the OE API and so the work around is a little nasty. I have also noticed that the OE API errors quite a lot.

Do you have any errors in your HA logs that relate to the integration that might relate to the issue? Am I correct in saying that the value of the entity becomes unknown rather than the entity becomes unavailable?

**Comment by realroywalker** [comment]
Yes correct from what I remember it goes to unknown rather than unavailable - I can't seem to see the history showing that in HA..  but will check next time it does it.
Had a quick look through the recent HA logs and apart from the occasional 502 (i'm guessing this is where the OE API is a bit flaky) the only other thing I notice is a few of these; 

`Failed to send request (https://api.octopus.energy/v1/products/SILVER-FLEX-22-11-25/electricity-tariffs/E-1R-SILVER-FLEX-22-11-25-E/standard-unit-rates?period_from=2023-04-10T23:00:00Z&period_to=2023-04-12T23:00:00Z): 404; {"detail":"Not found."}
Failed to send request (https://api.octopus.energy/v1/products/SILVER-FLEX-22-11-25/electricity-tariffs/E-1R-SILVER-FLEX-22-11-25-E/standard-unit-rates?period_from=2023-04-12T23:00:00Z&period_to=2023-04-14T23:00:00Z): 404; {"detail":"Not found."}
Failed to send request (https://api.octopus.energy/v1/products/SILVER-FLEX-22-11-25/electricity-tariffs/E-1R-SILVER-FLEX-22-11-25-E/standard-unit-rates?period_from=2023-04-13T23:00:00Z&period_to=2023-04-15T23:00:00Z): 404; {"detail":"Not found."}`

I now have the cost showing on my HA dashboard, so will hopefully spot pretty quickly next time it does it - i'll then confirm the state and see if anything in the log correlates to around that time.

**Comment by BottlecapDave** [comment]
Sorry for the late response. These errors from the APIs are probably the cause of the `unknown` values. It _should_ be falling back on old rates if a) valid in date rates have been previously downloaded and b) new rates are not available to download (like in your scenario). It attempts to redownload new rates every 30 minutes so it _should_ fix itself. Have you seen this behaviour again since reporting?
