### ISSUE TITLE
Offset the readings by one day

### ISSUE THREAD

**Issue by brewston** [BottlecapDave/HomeAssistant-OctopusEnergy#23]
**Describe the bug**
Since the previous_accumulative_consumption sensor collects yesterdays values, the graphs in home assistant are always one day out. eg the usage for Monday, is acually for Sunday etc.

**To Reproduce**
N/A
**Expected behavior**
Would it be possible to subtract 1 day from the data before passing to home assistant ? ie When a comsumption figure is collected on Monday morning, the figure is passed to HA as Sunday's figure.

**Home Assistant Logs**
N/A

**Comment by BottlecapDave** [comment]
Hello.

Unfortuately, this is a limitation of
a) the data that octopus energy provides and
b) the energy dashboard only working with "live" data.

It's because of these limitations which is why I put the disclaimer on the read me regarding adding these sensors to the energy dashboard.

I'll continue to keep an eye on the releases, and once this is possible, I'll add the ability

**Comment by brewston** [comment]
Thanks Dave.
