### ISSUE TITLE
Latest update lost Gas Tracker tariff

### ISSUE THREAD

**Issue by GeoffMorg** [BottlecapDave/HomeAssistant-OctopusEnergy#245]
**Describe the bug**

At start up time I get a message saying 

"Unknown tariff - Gas - G-1R-SILVER-FLEX-22-11-25-H.

"The tariff "G-1R-SILVER-FLEX-22-11-25-H" associated with your Gas meter has not been found. Click on 'Learn More' with instructions on what to do next."

This was working before the recent version of the integration.

**To Reproduce**

Use n account which has the Gas tracker tariff (happy to privately share mine if required)

**Home Assistant Version**

2023.5.3

**Integration Version**

7.1.3

**Fresh Install?**

After an upgrade?

**Home Assistant Logs**

N/A

I successfully use the URL https://octopus.energy/api/v1/tracker/G-1R-SILVER-FLEX-22-11-25-H/daily/current/0/1/ in a Perl script.

**Comment by BottlecapDave** [comment]
Hello and sorry for not responding to your message on the HA forums (it was on my list).

This logic hasn't changed, other than the frequency of which it checks. It gets reported if it fails to find the product via the API, which can also be caused by the API being down or the user not having an internet connection. There has been issues with the Octopus Energy API reporting server errors more frequently recently. I have it on my list to handle these scenarios better. It _shouldn't_ prevent any data from being retrieved if available and is used more as an indication to the user if they're on an unsupported tariff.

Do you have any other errors in your HA relating to the plugin?

**Comment by GeoffMorg** [comment]
Apologies for not coming back to you. This is resolved :-) I'm not aware of anything at my end which has changed and I didn't notice when it was fixed but all is good now.

Once again, apols for not coming back sooner.

**Comment by BottlecapDave** [comment]
No problem. Just wanted to make sure it was not an issue any more.
