### ISSUE TITLE
Failed to retrieve smart meter consumption data

### ISSUE THREAD

**Issue by mcknight89** [BottlecapDave/HomeAssistant-OctopusEnergy#256]
I've got a fresh install and having problems with getting the current consumption, in the logs I see:

`2023-05-30 17:29:42.685 DEBUG (MainThread) [custom_components.octopus_energy.api_client] Failed to retrieve smart meter consumption data - device_id: *REMOVED*; period_from: 2023-05-30T16:28:00Z; period_to: 2023-05-30T16:29:00Z
2023-05-30 17:29:42.687 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.current_consumption] Finished fetching current_consumption_*REMOVED* data in 0.419 seconds (success: True)`

The sensors have no data, I thought it might be that I am a Bulb customer that's been moved to Octopus, so I did the developer thing and checked out the API and found that it has consumption data:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/1823177/20882aee-2277-4ebe-941b-458aa82f992d)

Any help debugging would be really appreciated

**Comment by BottlecapDave** [comment]
Hello.

Various requests can fail from time to time for a number of reasons (e.g. lack of internet connection or Octopus Servers being down).  The current consumption data is requested via a graphql query, but it looks like the manual API request you're making is via the REST API which is for consumption data in the past. However in this scenario, it will try and fill in the missing data during the next sync (which is why it's a debug log). Is data for your Octopus Home Mini available within the app? Do you have any data available within HA?

**Comment by BottlecapDave** [comment]
Hi, the [Octopus Home Mini](https://octopus.energy/blog/octopus-home-mini/) is a special device which provides current consumption data via the APIs. Without it, you won't be able to get current consumption data via this integration. If you don't have it, you'll need to update the integration configuration and turn off the feature.

In terms of previous consumption data, you will need to follow the [guide](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/energy_dashboard.md#previous-day-consumption) to get this data into the energy dashboard. This data is usually available between 12 and 24 hours after the day.

Because this is an unofficial integration, Octopus support won't be able to help you with the integration.

**Comment by mcknight89** [comment]
I requested a Home Mini, I did shoot Octopus an email regarding the lack of consumption data which was defiantly better with Bulb, so might help my case to get one.

Going to close this off, But Thanks for all your help
