### ISSUE TITLE
Export Target Misbehaving

### ISSUE THREAD

**Issue by theneiljohnson** [BottlecapDave/HomeAssistant-OctopusEnergy#266]
I have an export target setup for 1 hour continuous, however today it didn't start at the most expensive time for export until I reloaded the integration. Then it didn't stop at the end, until I reloaded the integration again.

Also, the values for next time and next duration are unknown / 0

<img width="595" alt="image" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/27012389/614b05aa-1187-4225-aaec-5f8dbe32eb57">

<img width="533" alt="image" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/27012389/cdc71c74-b56a-4493-8466-6e6f4fb50809">

**Comment by BottlecapDave** [comment]
As per the bug report template, please provide

* Home Assistant Version
* Integration Version
* Fresh Install?
* Home Assistant Logs - Are there any related logs available in Home Assistant? Please follow the instructions as outlined in the [readme](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy#increase-home-assistant-logs).

**Comment by BottlecapDave** [comment]
The "current" data is only populated when you are currently within the chosen period (in your example between 5:30pm and 6:30pm BST) and the "next" data is only populated when the next slot has been calculated and is in the future. Due to the from/to times you've selected these won't be calculated until midnight tonight.

I've had other reports of other binary sensors not turning on/off when they should but it hasn't been consistent and I personally haven't seen it so can't track down why this is.

**Comment by theneiljohnson** [comment]
Thanks, it's been fine for a month or so, only yesterday it didn't start/stop. Exactly like you said, it's generated the slot at midnight for today so will keep an eye on it.
