### ISSUE TITLE
[FR] Getting more precise readings?

### ISSUE THREAD

**Issue by fonix232** [BottlecapDave/HomeAssistant-OctopusEnergy#275]
**Describe the feature**

I'm not exactly sure if it's supported by the GraphQL API (I can't seem to find any concise documentation, and I'm unfortunately not yet a GraphQL wizard), however the REST API does support very detailed meter reading (therefore consumption) details, broken down to even half-hourly readings. The REST API also supports grouping by period, and parameterising the requested period.

Therefore it should be possible that by implementing the REST API, to provide not daily level of consumption, but even hourly breakdowns, which would be immensely useful for the energy dashboard.

**Expected behavior**

The integration syncs regular half-hourly or hourly consumption data instead of daily (if half-hourly reading is enabled for the smart meter).

**Comment by BottlecapDave** [comment]
Hello. Precise readings are already available in a multitude of ways

1. The previous accumulative sensors have a half hourly reading already available as part of it's attributes
2. The sensors can then be setup in the [energy dashboard](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/energy_dashboard.md#previous-day-consumption). These work a little bit differently to setting up standard sensors due to the energy dashboard not being built for historic data (which is all that's available unless you have an OE Home Mini)

**Comment by fonix232** [comment]
That's precisely my problem.

The accumulative sensors seem to be updating at VERY random intervals and do not provide an appropriate status of consumption at any given point. Here is my current graph for the past 2.5 weeks:

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/371847/6cf0fcf1-20eb-4eff-8bca-a74469b80cfc)

As you can see there's one daily update, and it only imports the daily total (cumulative) usage - whereas if I were to query the REST API, I'd get a nice breakdown of the precise usage of every 30 minutes, which is what I'm looking for.

**Comment by BottlecapDave** [comment]
This is a limitation in HA sensors as they track live data changes and don't support importing historic data at such a breakdown. The "random" updates is due to when OE gets the data, which varies on a daily basis and I retrieve it as soon as possible. 

As already mentioned above the data is already available in the precision you request which is what was in the original request. If you don't want to use the energy dashboard you can still use the statistic sensor mentioned in the energy dashboard docs with a statistics graph card

```
chart_type: line
period: hour
type: statistics-graph
entities:
  - >-
    octopus_energy:electricity_xxx_xxx_previous_accumulative_consumption
stat_types:
  - state
days_to_show: 1
```
