### ISSUE TITLE
Octopus Agile: electricity current rate is wrong for the first 15-90 seconds of every 30 minutes interval

### ISSUE THREAD

**Issue by maksyms** [BottlecapDave/HomeAssistant-OctopusEnergy#327]
### Describe the bug

I'm using Octopus Agile and trying to build automation where one of the conditions checks the electricity current rate to switch on the load if it is below a certain value. However, the electricity current rate doesn't get updated for the current time period for anywhere between 15 and 90 seconds after the start of the interval. For example, here is the delay of 1 minute and 10 seconds:

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/595059/7a5814cc-9261-4247-a6ef-fb7a4543942b)

### Reproduction steps

Just open the graph of `Electricity Current Rate` sensor and look at the update timestamps.

### Expected behaviour

The current rate is correct as of the current time, without delays.

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-H

### Integration Version

v7.5.2

### Home Assistant Version

2023.7.3

### Fresh Install?

After upgrading

### Home Assistant Logs

Still obtaining, will update.

**Comment by maksyms** [comment]
Forgot to say: the current workaround is to use "next rate" instead of "current rate".

**Comment by BottlecapDave** [comment]
Hi there. All sensors are set to update every 1 minute. If any sensors take longer than this, then this is under the mercy of Home Assistant. This is by design to get a balance between speed of updates and not degrading people's home assistant instances. If you are wishing to make this more frequent then HAs recommendation is to use automations via https://www.home-assistant.io/integrations/homeassistant/#service-homeassistantupdate_entity
