### ISSUE TITLE
Question: Standing charge on Energy Dashboard

### ISSUE THREAD

**Issue by Coysh** [BottlecapDave/HomeAssistant-OctopusEnergy#330]
### Describe the bug

I've loved this integration so far. I'm early days with Home Assistant but this has really peaked my interest.

I've set it up so it brings in both Off Peak and Peak usage with costs in the Dashboards, and except the names being horribly long, it's been working.

I can't work out how to have it so that the total cost includes the additional rate of the standing charge.. Any advice would be appreciated!

<img width="1622" alt="CleanShot 2023-07-27 at 09 39 11@2x" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/5764356/0be3dd81-9d23-4619-b78e-48933a97e20e">

### Reproduction steps

Set up Off Peak / Peak energy usage.

### Expected behaviour

Show standing charge

### Tariff Code

E-1R-GO-VAR-22-10-14-B

### Integration Version

7.5.2

### Home Assistant Version

2023.7.3

### Fresh Install?

Fresh install

### Home Assistant Logs

N/A

**Comment by BottlecapDave** [comment]
Hi there. I'm sorry about the naming, but it was necessary to avoid any confusion/clashes. Unfortunately the energy dashboard doesn't support providing a standing charge rate. The peak/offpeak costs also don't include the standing charges because if I applied it to either or both of the sensors, I would end up getting bug reports that the data doesn't add up :)

If you're wanting to include the standing charge it in the energy dashboard with the peak/off peak breakdown, then I suggest you create a template sensor which takes one or both of those costs and add the value of the standing charge sensor. Then you can use the new template sensor in the energy dashboard instead of the sensors provided by this integraiton.

**Comment by Coysh** [comment]
Hey @BottlecapDave - just wondering if there are any methods of changing the name of the consumption sensors?
As you can see - the long names are making my tablet dashboard a little tricky to design!

<img width="1465" alt="CleanShot 2023-08-27 at 16 55 41@2x" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/5764356/e884135e-ac0c-4842-a617-67ae982d25b7">
