### ISSUE TITLE
Question: Home Mini Current Demand refresh interval

### ISSUE THREAD

**Issue by Reddax** [BottlecapDave/HomeAssistant-OctopusEnergy#331]
I have a Home Mini and have it all set up in the integration. But i've noticed the value only updates once every minute or so in HA, whilst the octopus app updates every 10 seconds. Is there a way to change the interval, or add a button onto my dashboard to force a value refresh?
Cheers

**Comment by BottlecapDave** [comment]
Hi There.

In the next update, there is a plan to support changing the interval level, but not to anything less than 1 minute. This is because I didn't want to flood the OE APIs and have the API removed. Since then OE have also [implemented rate limits](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/discussions/255) of 100 per hour, which is fine for the current integration as long as you only do electricity and don't use the app. I imagine the app has been updated to update every 10 seconds because they don't anticipate people to stay on the app for long periods of time (unlike HA which will be pulling data frequently without intervention). The API also doesn't give any indication on what the rate is in the response so if this changes I won't know without them specifying.
