### ISSUE TITLE
Power-Ups

### ISSUE THREAD

**Issue by onetoomany** [BottlecapDave/HomeAssistant-OctopusEnergy#375]
**Describe the feature**

Octopus have released PowerUps in SE England.

**Expected behavior**

I would expect a set of sensors similar to Saving Events; e.g.
Attribute | Type | Description
joined_events | array | The collection of saving sessions that you have joined
next_joined_event_start | datetime | The datetime the next saving session will start
next_joined_event_end | boolean | The datetime the next saving session will end
next_joined_event_duration_in_minutes | float | The duration in minutes of the next saving session

I don't know if Octopus support it, but a method of using HA to opt into the events.

**Comment by BottlecapDave** [comment]
Hi there.

I can't see anything in the API that is jumping out as power ups. It _might_ use the same API as the existing saving sessions, but someone who is signed up can confirm (possibly even you?)

I'll ask in the forums to see if anyone can point me in the direction.

**Comment by tpretz** [comment]
I think given the limited initial rollout its not in the API yet.
Signup and enrollment (there is a free period today) are via typeform rather than the octopus interface. 

And, the FAQ page does say:

```
Will I be able to track my progress through the app and dashboard?
Power-ups is brand new, and we’re starting it small. There’ll be no specific progress page or app.

We’ll email you to let you know how you’re doing every few weeks. As Power-ups grows, this might change!
```

I did take a look to see if there were any additions in my savingSessions (or any other) GraphQL response, but seems not.

I hope Octopus get this added to the API soon (assuming this discount project continues) as the ability to drive automations from this really is where customer savings will be most possible

**Comment by BottlecapDave** [comment]
Closing until an API exists.
