### ISSUE TITLE
Sensors for override rates

### ISSUE THREAD

**Issue by lildude** [BottlecapDave/HomeAssistant-OctopusEnergy#386]
**Describe the feature**

Expose the override gas and electricity rates as sensors.

**Expected behavior**

The method of comparing override costs as detailed in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/294 is great and really useful for assessing the daily cost, but I'd like to see how the override rates fluctuate and compare them on a similar graph.

This is particularly useful when assessing how often variable rates go over the fixed rates.

As a use-case example, I'm interested in tracking the gas price changes in the "Octopus Tracker February 2023 v1" (SILVER-FLEX-BB-23-02-08) tariff before switching.

**Comment by BottlecapDave** [comment]
Hello and thanks for the feature enhancement. While the data is not exposed explicitly, it is exposed as part of the `charges` attribute in the override cost sensors (see sub field of `rate`). This data will be a day late compared to the current rate sensor, but it too has the previous day's worth of data. You could then manipulate this data in a similar way to the [community graphs](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/community.md) to display them side by side.

Because the data is available in _some_ form, I'll add it to the backlog but there are other issues that need my attention first.

**Comment by BottlecapDave** [comment]
The rates are now available via the new [sensor](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/sensors/electricity.md#previous-consumption-override-day-rates). It might take up to 24 hours for this to be populated.
