### ISSUE TITLE
Rolling x hour window

### ISSUE THREAD

**Issue by onetoomany** [BottlecapDave/HomeAssistant-OctopusEnergy#411]
**Describe the feature**

Idea is that the agile price tracker gives me the best price in the next x hours, rather than across a 24 hr window.

I have a 5kWh battery, with general consumption of around 0.5kW, rising to 1kW in the evening - and more when the cooker is on. On Agile I will need to recharge this battery several times a day. The battery max charge rate is 100A, giving 1hr from empty to full, and will then last me between 5 and 10hrs of usage.

To make the most out of Agile, I would need to keep a rolling view of the prices and current charge level, and top up at the next best price in the time window. 

For example, I would have three or four rolling windows configured as different entities - best price in next 2hrs, next 5hrs and next 10hrs; depending on my charge level and whether there is a better price coming shortly, I can then build logic to say do nothing, charge a bit or fully charge.

To achieve this, the integration would need an optional "rolling window size" variable, with a default of 24hrs but with the ability to set it to a reduced figure such as a rolling 5hr window.

**Expected behaviour**

An additional optional box for Window Size on the entity configuration screen under "Re-evaluate multiple times per day" that is enabled when ticked.  Default of 24, min of 1, max of 24.

**Comment by BottlecapDave** [comment]
Hi there and thanks for the feature request. You could potentially do this now by adjusting the from/to times using the update config service, for the 2hr and 5hr periods (10hr would fail due to current restrictions in agile data).

Out of interest, what would you expect to be the behaviour if the best price constantly was the last rate in a period.
For example you had the following rates looking for the best rate within 2 hours

10:00-10:30 - 30p
10:30-11:00 - 29p
11:00-11:30 - 28p
11:30-12:00 - 27p
12:00-12:30 - 26p
12:30-13:00 - 25p
13:00-13:30 - 24p
13:30-14:00 - 23p

If you started looking at 10:00, the best price would be 27p (11:30-12:00). If it looked at 10:30, the best price would be 26p (12:00-12:30), etc. Therefore the target rate sensor would keep getting delayed until it turned on until the rates stabilized or started going up. I'm not sure if this would be the desirable behaviour. Or would you not evaluate a period until the last period had finished.

Also are you only every looking for the cheapest 30 minute period, or is this also being used in conjunction with the continuous/intermittent behaviour and customizable hours. All of these things in play could result in the sensor never turning or turning on during an expensive time due to other factors clashing with each other.

It feels like this is a different type of sensor if it was to be introduced, unless I'm missing something.

**Comment by onetoomany** [comment]
I was thinking this - if the rates are continuously falling, then I don't want to charge my battery yet - I'm better off delaying and using the spot price for that half hour for my general consumption. Once the prices hit bottom (at 13.30 in your example), then its worth pulling 5kWh from the grid.
Conversely, if prices are starting to rise as the evening peak approaches, I'm better off topping up my battery before they max out even though its far from one of the cheapest times of the day.

**Comment by onetoomany** [comment]
> @onetoomany although slightly off topic, Predbat will automate your Octopus Intelligent charging negating the need for such sensors.

This looks very impressive but as far as I can tell it only works with GivEnergy inverters?

**Comment by treforsouthwell-sifive** [comment]
> > @onetoomany although slightly off topic, Predbat will automate your Octopus Intelligent charging negating the need for such sensors.
> 
> This looks very impressive but as far as I can tell it only works with GivEnergy inverters?

Sadly yes, unless someone fancies porting it...

**Comment by onetoomany** [comment]
One other solution that might be easier to implement is a “time till next cheaper rate” (ideally, the next and the next +1) - so I can judge if it’s worth topping up the battery now and by how much based on usage vs holding out till there is a cheaper rate to top up with. Note, the result will always be the first next rate after the current rate that is lower than the current rate - not necessarily the cheapest.

If it’s the cheapest rate of all, then maybe return 999 or some large number.

Example: 
1. battery is half full, next cheaper rate in 2 hrs. Result: Do nothing as I’ve enough juice to survive till then.
2. Similarly, if the battery is empty, then I’m best of topping up by 1.5kw now, and potentially topping up again in 2hrs
3. Battery is empty, next cheaper rate in the next period. Result: do nothing as it will be cheaper to hold out

**Comment by MelHarbour** [comment]
I think I've got another (similar) use case for something like this, which would be the equivalent of:

I've got the dishwasher full and ready to go, I need it to run some time in the next (say) 6 hours from now, please run it in the cheapest half hour segment.

**Comment by darrenaf** [comment]
Would also like to add a vote for this type of detail.  Something like a sensor that gives the lowest price in the next 8 hours.  Currently there is a lowest price today, which is useful, but at 10pm, it doesn't make much sense.  

Currently I have a routine which switches on the electric water heating and turns off the gas heating if the price of electric drops below ( gas x 1.4 ).  This works but ends up heating prior to any price plunges.  Being able to predict these in the routine would be really useful.

**Comment by BottlecapDave** [comment]
A new version of the target rate sensor for this is now available in [v13.0.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.0.0). See https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/rolling_target_rate/ for more details.

**Comment by billmichell** [comment]
Looks like when set to Continuous reclculation, this sensor never turns on - because the current period started in the past. I don’t think this is what was intended. At least, I don’t find it terribly useful

**Comment by BottlecapDave** [comment]
Sorry you're seeing this behaviour. The sensor should turn on at least once otherwise like you said it isn't very useful.

I'm tracking the progress at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/1030, which I'll try and look at within the next week.
