### ISSUE TITLE
Mixed numerical values for comparable values

### ISSUE THREAD

**Issue by U32Frank** [BottlecapDave/HomeAssistant-OctopusEnergy#439]
### Describe the bug

the kW/h appears to be stored in an inconsistent way making it hard to do comparisons between different values in scripts,

### Reproduction steps

entity_id: sensor.octopus_energy_electricity_19l3408548_2342802280410_current_rate 

Value of this entity could be  = 0.1456

entity_id: sensor.octopus_energy_electricity_19l3408548_2342802280410_current_rate 
attribute: current_day_average_rate 

Value of this entity attribute could be = 16.56

This prevents us from using a simple numeric state script as we need to convert one of the values by multiple or divide by 100.

### Expected behaviour

I would expect them to be consistent

entity_id: sensor.octopus_energy_electricity_19l3408548_2342802280410_current_rate 

Value of this entity  = 0.1456

entity_id: sensor.octopus_energy_electricity_19l3408548_2342802280410_current_rate 
attribute: current_day_average_rate 

Value of this entity attribute should be = 0.1656

### Tariff Code

N/A

### Integration Version

8.3

### Home Assistant Version

latest

### Fresh Install?

Fresh install

### Home Assistant Logs

N/A

**Comment by BottlecapDave** [comment]
Hello. The reason for this is because it calculates the average/min/max from the raw data from OE, which is presented in pence. However, HA only supports sensors in GBP which is why it's converted. I agree that the inconsistencies are not great. I'll fix the attributes I'm in charge of, but I'll need to think about the raw data from OE as this could have undesired effects. Either way, this won't change won't come in straight away as it'll be a breaking change and I like to try and stack them up to minimise impact to users.

**Comment by BottlecapDave** [comment]
I'm trying to be careful with not putting everything into their own senros, as with a normal electricity/gas setup there's already around 40. I only look at rehousing data if they're causing issues (e.g. rate information), and as HA provides a variety of ways of extracting this information (e.g. automations of template sensors) and these attributes are related I don't feel this warrants it's own sensors at the moment.

**Comment by BottlecapDave** [comment]
I've had a few additional reports around inconsistencies, so I've created https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/481 to consolidate them all. I'm therefore closing this issue, and request that you follow that issue for updates.
