### ISSUE TITLE
Support opting into saving sessions via service

### ISSUE THREAD

**Issue by BottlecapDave** [BottlecapDave/HomeAssistant-OctopusEnergy#487]
**Describe the feature**

I want to be able to see upcoming events and automatically opt into them via the integration.

**Expected behavior**

A new service for opting into an event

A new event entity which displays upcoming and current events (this should power the saving session binary sensor)

**Comment by BottlecapDave** [comment]
Breaking change as existing saving session entity should have `joined_events` attribute removed so we don't end up with the same issue as current rate and all rates

**Comment by Gadgit83** [comment]
Assuming this is a feature to automatically opt in to all savings sessions? This would be great, didn't even know there was an API service for that. Have you seen the new 'free energy' sessions through Octoplus too? I was just looming to see if theres an API for those yet but couldn't find any details, would be similarly great if your integration supported auto opting in to those, and then reporting when its starting/started similar to saving sessions so that we can switch on home energy storage etc.

Might upset Octopus a little if it is over used, especially if there aren't actually regular savings/extra consumption.

Great integration though, you must have single handedly saved a good few tonnes of CO2!

**Comment by BottlecapDave** [comment]
My plan is to provide the tools and examples for opting into the saving sessions (service and sensor for events the user has and hasn't opted into), as there might be other factors outside of the integration that might determine if an event should be joined. I'm not too sure why you have to opt in, as there doesn't seem to be a penalty for not saving anything.

As for the free sessions, last time I checked there was no API available as they were alerting users via email due to the small areas it was available within. But I continue to look at the API from time to time (or when people let me know) to see supported features.

**Comment by BottlecapDave** [comment]
This is now available in v9.0.0 release.
