### ISSUE TITLE
Virtual export meter without official export meter 

### ISSUE THREAD

**Issue by skundrik** [BottlecapDave/HomeAssistant-OctopusEnergy#508]
**Describe the feature**

Have a "virtual" export meter device for people who don't have an official export meter with Octopus but are still exporting under deemed export. This would improve energy dashboard information.

**Expected behavior**

Virtual export meter could use Octopus mini current demand to try to provide amount of exported energy when demand shows as negative.

**Comment by BottlecapDave** [comment]
Hello. Sorry for the very late response. Could you elaborate on how you see this working? For people with export meters, they tend to use other integrations that are native to their hardware.

If the idea is to use the demand data, then it can't be updated frequently enough to produce an accurate reading due to rate limiting.

**Comment by BottlecapDave** [comment]
Closing as not enough information
