### ISSUE TITLE
Naming of Octopus Energy Saving Sessions entity

### ISSUE THREAD

**Issue by Gary-Manuel** [BottlecapDave/HomeAssistant-OctopusEnergy#541]
**Describe the feature**

It has been noted following the first use this year of the Octopus Savings Session sensor that there are some installations where the sensor is named "binary_sensor.octopus_energy_saving_sessions" and some where it is named "binary_sensor.octopus_energy_saving_session". Note the difference is the "s" at the end. This is causing problems with Home Assistant automations set up to use this sensor and it's attributes to trigger the required actions before / during the saving sessions. The naming remains without the "s" despite updating to the latest issue. Uninstallation and reinstallation renames to include the "s". It is suspected that the difference is due to an historic name change which is not being aligned during regular updates.

**Expected behaviour**

Is there any way to force a renaming along with a "breaking change" tag during the next convenient update?

I am aware of the forthcoming additions / changes affecting this entity and it's attributed due to work being done on opting in etc and am hoping that this work will correct the issue anyway, but raising it as a feature request in case it doesn't.

P.S. Thanks for the brilliant work you are doing. Your work is much appreciated.

**Comment by BottlecapDave** [comment]
Hello. I try and outline all breaking changes in the changelogs, but some will potentially fall through the net. This one in particular went from `season_savings` when it was first introduced to `saving_sessions` last year (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/commit/3264ec792d0bb7f907c8f7990eccdf56590b112b), but I find no record of it ever matching that name. The only thing I can think of is where it may have changed during [7.0.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/CHANGELOG.md#700-2023-04-18), where there was a bug where the name was derived from the name of the entity instead of the defined id I had specified. This was highlighted as a possible side effect, where users should have checked their entities names.

The next release, will indeed change the name again I'm afraid, and that release will be marked as breaking for this (among other) reasons.

**Comment by Gary-Manuel** [comment]
Thanks for the rapid response and closure. Keep up the good work!
