### ISSUE TITLE
Saving Session binary sensor issue

### ISSUE THREAD

**Issue by alfwro13** [BottlecapDave/HomeAssistant-OctopusEnergy#561]
### Describe the bug

Today octopus at very short notice announced saving session in my region from 13:10 - 14:10. I joined using automation as per your documentation - that worked fine.
However the binary sensor: binary_sensor.octopus_energy_<account>_octoplus_saving_sessions stayed off until 13:30:
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/10945277/42d513f4-7449-451a-827a-b8b5362f340e)

However it turned back to off as expected at 14:10

### Reproduction steps

wait for next saving session and monitor the binary sensor ?

### Expected behaviour

it should switch on when saving as indicated by the saving session start time

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-J

### Integration Version

9.0.1

### Home Assistant Version

2023.11.3

### Fresh Install?

After upgrading

### Home Assistant Logs

n/a

**Comment by alfwro13** [comment]
Prior to the event the binary sensor in question had the following attributes:

binary_sensor.octopus_energy_<id>_octoplus_saving_sessions
attributes:
current_joined_event_start: "2023-11-23T13:10:00+00:00"
current_joined_event_end: "2023-11-23T14:10:00+00:00"
current_joined_event_duration_in_minutes: 60
next_joined_event_start: null
next_joined_event_end: null
next_joined_event_duration_in_minutes: null
data_last_retrieved: "2023-11-23T13:00:41.304627+00:00"
last_evaluated: "2023-11-23T13:04:41.305042+00:00"
icon: mdi:leaf
friendly_name: Octopus Energy <ID> Octoplus Saving Session

**Comment by BottlecapDave** [comment]
Hello. This is related to https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/560 as the background service obtains the updated data every 30 minutes so not to flood the API (which is brittle) and the outgoing/incoming data for the user. 

Because todays event was short notice, it didn't give it enough time to pull the updated data. I will have a look at trying to force the refreshing of the data without flooding the API.

**Comment by BottlecapDave** [comment]
This should now be resolved in the latest update (v9.0.2). It might take a couple of minutes for the data to update after using the service. Obv the proof will be in the pudding for the next saving session, so it might still need some tweaks.

**Comment by thewishy** [comment]
If I could make an observation. I've setup my system to feed the data into the local calendar at time of discovery and subscription rather than work directly off the sensor. (Well, subject to the automation actually working).  

There are a number of advantages to working off the calendar
- Better visibility and predictability. You can see the event easily
- Standard functionality which is easy to test without needing a "real" event or a proper test rig
- Ability to create automation with a time offset vs the next or recently finished calendar event. 

I'm using the offset to
- Turn up the heating an hour before the event
- Clear the battery reserve and switch off the heating 30 seconds before the event
- Start max export once the event starts
- Return to normal at the end of the event

The main thing I'm missing is automation to check that the event moves from "available" to joined after the data refresh

Perhaps this would be a better general approach to reference in the documentation examples?

**Comment by BottlecapDave** [comment]
For todays event the event information updated as expected, so closing this issue.
