### ISSUE TITLE
Ability to add multiple accounts

### ISSUE THREAD

**Issue by apbarratt** [BottlecapDave/HomeAssistant-OctopusEnergy#57]
As someone who helps my not-so-technically-minded family members monitor their energy usage, I would like to be able add multiple Octopus Energy API keys so that I may add their data to my home assistant.

(in the meantime, if this is already possible with yaml files etc, I'd appreciate an example configuration of how to do this:)

**Comment by apbarratt** [comment]
Additionally, the current form that appears when attempting to add the integration a second time is a little confusing, I'm not entirely sure what it is.

**Comment by BottlecapDave** [comment]
Hi @apbarratt. Thanks for the request and I can fully sympathise with being the technical gatekeeper :)

Unfortunately to support this would be quite a big rewrite, there hasn't been any other requests and my time at the moment is limited due to other committments. 

However, I'll keep this ticket open and see if anyone else upvotes this request. I'm also happy to accept a PR if you (or anyone else) are wishing to make the change.

> Additionally, the current form that appears when attempting to add the integration a second time is a little confusing, I'm not entirely sure what it is.

As per the readme, this is used for setting up target rate binary sensors. These sensors monitor your rates and turn on when the price is at it's lowest. These can then be used to turn on/off devices via automations. For example, I use mine to turn on robot vacuum cleaners and washing machines.

Sorry this probably wasn't the answer you were hoping for.

**Comment by cscashby** [comment]
I appreciate this is a fair bit of work, but I'd love this too - I manage a number of properties and having some visibility of their usage in HA would be amazing.

Even as the OP says a quick guide to manual .yaml config would be super useful.

**Comment by cscashby** [comment]
> Additionally, the current form that appears when attempting to add the integration a second time is a little confusing, I'm not entirely sure what it is.

This is documented - it creates a time of use sensor which is 'on' at the cheapest available requested time slot.
