### ISSUE TITLE
Octopoints changed

### ISSUE THREAD

**Issue by darrenaf** [BottlecapDave/HomeAssistant-OctopusEnergy#613]
### Describe the feature

There currently isn't a way to notify when Octopoints are added or removed.  Both of the current attributes trigger randomly when there is no change to the value.

### Expected behaviour

A changed value would trigger when points are added or removed.

### Use Case

Ability to send a notification when this data changes

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs) and confirmed it does not already exist
- [ ] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. This is by design of HA entities and their attributes. The entities themselves have two attributes, `last_evaluated` and `data_last_retrieved` which trigger roughly every minute and every 30 minutes respectively. If you have an automation with no `from` or `to` defined, then they will trigger everytime the state **or** attributes change. As per the [HA docs](https://www.home-assistant.io/docs/automation/trigger/#state-trigger) you will need to set `from` or `to` to `null`. If you are doing this from the UI, then you need to set `from` or `to` to `Any state (ignoring attribute changes)`.
