### ISSUE TITLE
No Export Meter measurement

### ISSUE THREAD

**Issue by pacemaker82** [BottlecapDave/HomeAssistant-OctopusEnergy#727]
### Describe the bug

I have all the data for the agile export tariff, yesterdays export kWh and cost data, but cannot seem to get the total export kWh for today. I have **Current Accumulative Consumption** for Import, but no Export equivalent. **Current Accumulative Consumption** isn't reducing to take into consideration export. I can see that "Current Demand" for the mini is showing -2000w which is accurate

### Reproduction steps

Added from HACS. Set Octopus Mini ON and provided API and account references. View entities

### Expected behaviour

Find an entity/sensor on export device for the exported kWh today.

### Tariff Code

unknown

### Integration Version

10.0.3

### Home Assistant Version

2024.1.5

### Fresh Install?

Fresh install

### Home Assistant Logs

none

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. The octopus home mini unfortunately doesn't expose export meter consumption information. I'll update the docs with this information.

**Comment by acormack** [comment]
Hi Dave,

I have a Home Mini and using your integration can see the "Current Consumption Electricity" entity in HomeAssistant whenever I am importing.  Thanks for all the effort you have put into this project.

On the Octopus Energy website /dashboard/new/accounts/{id}/consumption/home page where it displays "Live Use" updating every 10 seconds - it has the same positive figure when importing, but it also shows a negative number when I am exporting.

I suppose they must be using a private undocumented API to access this figure.  Do you think they might change the import figure to a signed integer in future rather than add "current entities" on the export meter?  

This might reduce server load as otherwise you would have to make two API calls since you will never know whether the live result will be an import or export.  

Thanks again for all your work on this,

Alec
