### ISSUE TITLE
Indicate where data is missing and optionally repoll to download missing data when available

### ISSUE THREAD

**Issue by jwt99412** [BottlecapDave/HomeAssistant-OctopusEnergy#753]
### Describe the feature

Possibly add a sensor to indicate where data is missing for a 24 hour period as this sometimes occurs where Octopus may update the import/export data up to 48 hours later.
Where data are missing this could be used to repeal the data source at a later date when the data appears.

### Expected behaviour

New sensor would indicate missing data if no data received in a 24 hour period. If a control to poll for missing data were available as a service, this could be done manually by the user or in an automation.

### Use Case

Very occasionally my data from Octopus is posted very late and does not come through for a couple of days. Octopus only say within 24-48 hours. The issue happened again this Monday 12/2 where import data and Gas data came through very late (22:00 or so) and export data not at all. The idea would be at least to indicate to the user that the data was missing and optionally refetch.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. Thanks for the feature request. At this time, I'm not planning on including this as it can be accomplished easily with the available entities and the timeframe might want to be different for different people which would complicate the integration.

To achieve this now, you can setup a template sensor with the following setup

```
{{ now() - state_attr('sensor.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}_{{MPAN_NUMBER}}_previous_accumulative_consumption', 'last_evaluated') >= timedelta(hours=24) }}
```
or for gas
```
{{ now() - state_attr('sensor.octopus_energy_gas_{{METER_SERIAL_NUMBER}}_{{MPRN_NUMBER}}_previous_accumulative_consumption_m3', 'last_evaluated') >= timedelta(hours=24) }}
```

This would represent the binary sensor you're after, which you can then use as a trigger for an automation to alert you as you see fit.

There is already a sensor for [back filling previous consumption/cost](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/services/#octopus_energyrefresh_previous_consumption_data). This will only update the data for the external statistics (which are recommended for energy dashboard) due to importing historic data for entities within HA is unreliable.

**Comment by jwt99412** [comment]
David,

Thanks for this.

I refreshed as you state above using a manually triggered automation and it updated the missing half hour data but not the once per day data. That is ok for what I wanted. Thanks for looking at it and pointing me at the workaround.

Cheers,

Bill.
