### ISSUE TITLE
Target Rate Sensor with dynamic hours

### ISSUE THREAD

**Issue by beginner2047** [BottlecapDave/HomeAssistant-OctopusEnergy#837]
### Describe the feature

Currently, the hours is static field. Enhance this field can be static or dynamic. Dynamic value should refer to other entities number values

### Expected behaviour

The behavior should be same as static value. The target rate will search the best number of hours according to this dynamic value.

### Use Case

e.g. 1.EV charger, we can calculate the number of hours according to battery level of the car. If the battery of ev car is 70%, It only a few hours to fill up. If the battery of EV car is very lower (20%), it needs more hours. If static     to define 5 hours, but the car only need 2 hours to fully charge, it means the car is not charged at the cheapest of 3 hours. The first two hours can be the highest of the cheapest range
2. Washer, they have different mode and different running time for different mode, when i select the mode, the number of hours will be changed for corresponding mode and search the cheapest time. 

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [ ] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. The config for the target rate sensor is already getting quite chunky. If a certain attribute is exposed to be fed from another entity, then people will expect other attributes to be fed from other entities.

Instead, you can achieve this today with the use of [update target config service](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/services/#octopus_energyupdate_target_config). You can use this service as part of an automation (e.g. when your washing machine mode changes, calculate the required hours and call the service).

Because of the presence of this service and complexity of monitoring other entities and the target rate config itself, there are no plans to implement this feature.
