### ISSUE TITLE
10.3.0 - Unexpected debug output in logs

### ISSUE THREAD

**Issue by thewishy** [BottlecapDave/HomeAssistant-OctopusEnergy#843]
### Describe the bug

Upgraded 10.1.0 to 10.3.0 today.
- Octopus IO
- Octopus Mini
- Home Assistant Core, 2024.4.3

Since the upgrade, the log files seem to include datapoints which are being gathered from the Octopus API. Debug logging is not enabled. 

### Reproduction steps

Unclear - Upgraded from 10.1.0

### Expected behaviour

Debug logs only present when debug logging enabled?

### Tariff Code

 E-1R-INTELLI-VAR-22-10-14-J

### Integration Version

10.3.0

### Home Assistant Version

2024.4.3

### Fresh Install?

After upgrading

### Home Assistant Logs

Apr 18 21:23:10 nandi hass[416880]: https://api.octopus.energy/v1/gas-meter-points/3****7/meters/G4P*****/consumption?period_from=2024-04-16T23:00:00Z&period_to=2024-04-17T23:00:00Z
Apr 18 21:23:10 nandi hass[416880]: https://api.octopus.energy/v1/gas-meter-points/3****7/meters/G4P****/consumption?page_size=1
Apr 18 21:23:10 nandi hass[416880]: 2024-04-16 23:00:00+00:00
Apr 18 21:23:10 nandi hass[416880]: 2024-04-16 23:30:00+00:00
Apr 18 21:23:10 nandi hass[416880]: 2024-04-17 00:00:00+00:00
.. Repeats with various timeblocks for hundreds of lines ...

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by pcb1962** [comment]
I found the same, lots of lines with just a timestamp repeating at 1 minute intervals.
Downgraded to 10.2.1 and it's back to normal.

**Comment by pdcastro** [comment]
Apparently coming from [`utils/__init__.py` line 76](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/v10.3.0/custom_components/octopus_energy/utils/__init__.py#L76):
```py
        print(rate["start”])
```

Already fixed in commit [c028b15](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/commit/c028b159e7594f29e044f27d01a80f3ccab2a9f9#diff-c2df2c77c5df700e5393cf58768fae262a97af7264abe8d390ba089eb1b4fd38L76) in the [develop](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/commits/develop/) branch, but not yet released.

**Comment by BottlecapDave** [comment]
Hello and sorry about this. I've released v10.3.1 which should remove these statements
