### ISSUE TITLE
Incorrect binary_sensor.octopus_energy_electricity_*_*_off_peak next end

### ISSUE THREAD

**Issue by plord12** [BottlecapDave/HomeAssistant-OctopusEnergy#870]
### Describe the bug

I noticed that binary_sensor.octopus_energy_electricity_*_*_off_peak next end is getting set incorrectly.   

I'm on octopus intelligent and I expect start to be at 23:00 and end at 05:30.  But I'm seeing this attribute getting updated incorrectly at 23:30.

<img width="1237" alt="Screenshot 2024-05-14 at 23 38 51" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/63543143/b06ed9ea-19e6-40e6-bef8-ebbaf0560fdf">

### Reproduction steps

I expect if you are also on octopus intelligent, you can trigger on changes to binary_sensor.octopus_energy_electricity_*_*_off_peak and print off the values

### Expected behaviour

Next end should be set to either unknown or 05:30

### Tariff Code

E-1R-INTELLI-VAR-22-10-14-H

### Integration Version

11.0.0

### Home Assistant Version

2024.5.3

### Fresh Install?

After upgrading

### Home Assistant Logs

none

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Upon looking at this more closely, this is as expected and due to not having all of the available data. 

There is nothing in the available data that tells me what a "typical rate schedule" looks like for a tariff. There is also nothing that states if the rates change half hourly, daily or for the full term of the tariff. So this is inferred from the available rates. The integration only ever pulls the data for 72 hours (yesterday, today and tomorrow). When you looked at the attribute (14th), you only had up to midnight for the following day (16th 00:00:00). If you looked at the sensor after midnight after it retrieved the next set of rates, then it would correctly show 05:30. 

Therefore this is by design and won't be changed.
