### ISSUE TITLE
Agile Rates Card(s) - Ability to view in dashboard upcoming rates

### ISSUE THREAD

**Issue by andyvirus** [BottlecapDave/HomeAssistant-OctopusEnergy#88]
Feature request.

Would it be possible to have an entity that showed the upcoming rates which could then be used in a card on a dashboard.
What I ideally want is something similar to what https://github.com/markgdev/home-assistant_OctopusAgile has done.
The dev no longer maintains that project and only caters for Import not Export/outgoing.
I can see you provide both import and export rates in the Atributes of Current Rate but I am looking for a nice way to view these rates on a dashboard, ideally like the card provided in the other project that is no longer maintained as that has configureable colour coding when the rate is low, medium or high (Green, Yellow, Red). If the sensor and attributes were the same between the 2 I could just point that card at your rates entity but there is significant differences.

The other uses the format:
2022-11-09T22:30:00Z
17.16
2022-11-09T22:00:00Z
23.35
2022-11-09T21:30:00Z
23.15
2022-11-09T21:00:00Z
27.56
2022-11-09T20:30:00Z
23.71
2022-11-09T20:00:00Z
24.48
2022-11-09T19:30:00Z
20.71
2022-11-09T19:00:00Z
31.75
2022-11-09T18:30:00Z
35

While yours uses the attributes in a sub attribute called rates and in the format of:

Rates
- from: '2022-11-08T00:00:00+00:00' to: '2022-11-08T00:30:00+00:00' rate: 8.1585 - from: '2022-11-08T00:30:00+00:00' to: '2022-11-08T01:00:00+00:00' rate: 11.025 - from: '2022-11-08T01:00:00+00:00' to: '2022-11-08T01:30:00+00:00' rate: 10.8885 - from: '2022-11-08T01:30:00+00:00' to: '2022-11-08T02:00:00+00:00' rate: 9.8805 - from: '2022-11-08T02:00:00+00:00' to: '2022-11-08T02:30:00+00:00' rate: 10.8255

So not trivial to convert (for me anyway).

This is the only thing I use the other HACS plugin for, the rate card as your plugin provides everything I need other than that, and your update and sensor values remain even after a reboot so using your values would be advantageous.
![Screenshot 2022-11-08 at 17 06 55](https://user-images.githubusercontent.com/11655424/200629885-d6c930cf-878b-4646-88f2-3774de201d62.png)
![Screenshot 2022-11-08 at 17 06 38](https://user-images.githubusercontent.com/11655424/200629898-f7cc43a8-095e-460e-8aa9-e68bbe120852.png)
![Screenshot 2022-11-08 at 17 06 15](https://user-images.githubusercontent.com/11655424/200629901-c8aa285d-0eae-4baa-b769-bdc3a15cca5d.png)
![Screenshot 2022-11-08 at 17 08 58](https://user-images.githubusercontent.com/11655424/200630229-52571748-4e66-4fcd-9c69-bfa0018dc310.png)

Screenshots for reference. Thank you for your epic work!

**Comment by usbrit** [comment]
I would love thus too. Have the same situation where I just use the rate card from the old integration!

**Comment by andyvirus** [comment]
Oh and Blue for negative pricing such as tonight (not seen that before till today)

**Comment by BottlecapDave** [comment]
I'm not planning on changing the current setup because it would be a breaking change for existing users. If someone would like to port the card across (licencing/permission from author permitting) and make a pull request, I'm happy to take a look at the PR and include it.

**Comment by slip83** [comment]
I'd like this feature as well... The mentioned tariff integration does not work for me (I'm not an advanced user)

**Comment by alfwro13** [comment]
That feature would be amazing  - I have just moved to Octopus Agile and I am scratching my head how to get a graph or a table of upcoming/past rates

**Comment by lozzd** [comment]
I've modified the Javascript from https://github.com/markgdev/home-assistant_OctopusAgile/tree/master/custom_cards to work with this integration and added a couple of new features (ability to hide rates before `$now` and show the day of week next to the time, since this integration retrieves a lot more rates than the other one)

I'm more than happy to share it, the question now is logistics...

@BottlecapDave are you familiar enough with HACS to say whether you can have a custom card and an integration in the same repo? From the reading of their docs it seems like no? In which case I'll publish my own HACS repo for this custom card using your integration as the data source.

**Comment by lozzd** [comment]
Okay - I published this in my own repo because I think you can't join Integrations and Cards anyway. 

https://github.com/lozzd/octopus-energy-rates-card

Please feel free to give it a shot and let me know how it goes.... feedback welcome (in that repo I guess) 

@BottlecapDave let me know if you want me to PR the README in here to link to it, or want to keep them totally separate. Then you can close this :)

**Comment by slip83** [comment]
OMG! At last. Thanks a million Laurie!

**Comment by mdeakin99** [comment]
I second this.  This is brilliant.

On 1 Feb 2023, at 21:29, slip83 ***@***.***> wrote:

﻿

OMG! At last. Thanks a million Laurie!

**Comment by BottlecapDave** [comment]
@lozzd Thanks for taking this upon yourself! I'll update the readme soon with a link to your implementation :)

**Comment by BottlecapDave** [comment]
I've added this to the readme, so closing now.
