### ISSUE TITLE
Unable to query smart meter telemetry data

### ISSUE THREAD

**Issue by holdestmade** [BottlecapDave/HomeAssistant-OctopusEnergy#935]
### Describe the bug

Getting this warning in my log a 13-15 times an hour

### Reproduction steps

na

### Expected behaviour

na

### Tariff Code

E-1R-FLUX-IMPORT-23-02-14-M

### Integration Version

11.2.0

### Home Assistant Version

2024.6.3

### Fresh Install?

Not specified

### Home Assistant Logs

`2024-06-25 16:23:33.487 WARNING (MainThread) [custom_components.octopus_energy.api_client] Errors in request (https://api.octopus.energy/v1/graphql/): [{'message': 'Unable to query smart meter telemetry data.', 'locations': [{'line': 2, 'column': 2}], 'path': ['smartMeterTelemetry'], 'extensions': {'errorType': 'SERVICE_AVAILABILITY', 'errorCode': 'KT-GB-4039', 'errorDescription': ''}}]`

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by psfshr** [comment]
Probably looking like an Octopus issue. I'm seeing the same, plus also a set of "502 Bad Gateway" errors and other timeouts.
I've been seeing long timeouts intermittently since the 19th, but it's really got worse in the last 36 hours.
<img width="905" alt="Screenshot 2024-06-25 at 18 05 37" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/9417766/fe5fcf02-2d72-4258-a6bd-ca1c4ff41bb6">
(Graph is basically showing latency to retrieve "current_demand" based on "data_last_retrieved" attribute)

**Comment by BottlecapDave** [comment]
Yeah I'm afraid that issue (and any status above 500) that comes from the OE API is out of my control. I raise a warning so that people can see why they're data might not be updating.
