### ISSUE TITLE
setting target rates before 4pm and after middnight not working, even when data available

### ISSUE THREAD

**Issue by f1wade** [BottlecapDave/HomeAssistant-OctopusEnergy#942]
### Describe the bug

If I set the min target time at 15:59 and max as 23:01 it will fail saying:
`Target time not fit for agile tariffs. Please consult target rate documentation for more information.`

but the times are all available at its 16:15pm, and I want it to include 1600 + in an automation.

But If I put 16:00 and 23:01 it will work, and if I put 15:59 and 23:00 it will work.

Can this be looked into why its throws this error, when the data is available to work this out.

I am on v8.2.0 so this may have been fixed, I'll update and find out in time.
but if anyone has knowledge please add a comment.

### Reproduction steps

added

### Expected behaviour

to work out the target rates

### Tariff Code

TODO

### Integration Version

v8.2.0

### Home Assistant Version

todo

### Fresh Install?

Not specified

### Home Assistant Logs

todo

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello. This is by design. The reason can be found in the [docs](http://127.0.0.1:8000/setup/target_rate/?h=agile#agile-users) and is due to a combination of reasons

* Target rate sensors will only evaluate once all rate information is available.
* Agile data is not always available at 4pm on the dot (there's been times when it's been delayed to 6pm for instance) and only available to 11pm the following day. 

This caused issues in the past where the sensor would pick the best time, but the best time could have been at the start of the evaluation period and therefore had already passed. This resulted in the sensor looking like it had not turned on and missed the selected times. This was added to safeguard and prevent those scenarios.

What are you trying to achieve during these times?

**Comment by f1wade** [comment]
That's interesting @BottlecapDave, sounds like your doing too stop almost the thing in trying to do.

So I'm trying to reevaluate based on forecast, and if at 4.05pm it thinks it needs to charge overnight, it'll go back 30 mins and cover till 9am, so then if the 4pm - 430 slot is the cheapest it'll start charging straightaway.
I have 2, 1 till 4pm and 1 till 9am.
But the pre 4pm till after midnight, won't even set, so then when data is available it would recalculate.

**Comment by f1wade** [comment]
@BottlecapDave maybe I didn't detail enough, I have an automation that sets these values when it calculates it will need charging, and I only set it to 30 mins before now, so the earliest half hour would be the current half hour.
So it would turn on straight away, but usually it over 6h later in the middle of the night, but sometimes it will take a charge at 340pm till 4pm.

I just think it should be allowed, or have a setting to turn it off, the n if users are aware they can use as they want, and should understand the pros and cons of settings.

**Comment by BottlecapDave** [comment]
> I have an automation that sets these values when it calculates it will need charging, and I only set it to 30 mins before now, so the earliest half hour would be the current half hour.
So it would turn on straight away, but usually it over 6h later in the middle of the night, but sometimes it will take a charge at 340pm till 4pm.

If this automation is always run at 16:05, then this could just set the target rate sensor with a start of 16:00. If this automation runs at several times during the day, then the start/end time could be adjusted based on the time (e.g. if before 16:00 then start/end is now minus 30 minutes/16:00 or after 16:00 then start/end is 16:00-09:00). If you post your automation, it might be better to suggest alternatives.

> I just think it should be allowed, or have a setting to turn it off, the n if users are aware they can use as they want, and should understand the pros and cons of settings.

As mentioned, this is here to protect users against picking times where the data is not available straight away causing the sensor to pick times in the past when the data becomes available and not turning on. It was introduced due to a number of issues raised. I'd like to see the automation before thinking about introducing a way of ignoring the error.

**Comment by f1wade** [comment]
I've figured a scenario this would be really useful for.
Maybe add under a flag.

But if you have rates from 11am till 11pm, and the cheapest rates are at 9-10pm, that it would be good to hold off charging until then.
Rather than having a charge around 3pm, when you can wait till 9pm for a cheaper charge.

Does that make sense.

**Comment by BottlecapDave** [comment]
> But if you have rates from 11am till 11pm, and the cheapest rates are at 9-10pm, that it would be good to hold off charging until then.
Rather than having a charge around 3pm, when you can wait till 9pm for a cheaper charge.

You can set the evaluation period to be 23:00-23:00 (or 22:00-22:00 or 21:00 to 21:00, etc). This would then pick the best rates you've specified. You just can't set it to look at the specified overlapping period because while you might have the agile rates on time today, you might not tomorrow and the sensor has to work every day otherwise people won't rely on it. 

> So I'm trying to re-evaluate based on battery forecast, and if at 4.05pm it thinks it needs to charge overnight, it'll go back 30 mins and cover till 9am, so then if the 4pm - 430 slot is the cheapest it'll start charging straightaway.
I have 2, 1 till 4pm and 1 till 9am.

Lets take your original scenario. If the integration supported setting the target rate sensor to 16:00-09:00, then at 16:00 you don't necessarily have the full window of rate information available (only up to 23:00). The sensor will therefore not evaluate until it has all rate information between 16:00 and 09:00. If the agile data came through at 18:00 and it worked out that the best slot was at 16:00-16:30, it won't come on because it's in the past and you _might_ raise the issue that the target rate sensor is broken and never came on (because the attributes stated it should have come on at 16:00 even though it was in the past when it calculated it). In reality, the best rate is rarely between 16:00 and 23:00.

In the next release (beta currently available), there is a different type of target sensor which looks at rate information x hours ahead instead of a time window. This might be better suited for your scenario as you could make it always look say 12 hours ahead and find the best time. Then once the best time has passed it will find the best time again 12 hours ahead.
