### ISSUE TITLE
Remove attributes from Current Demand Sensor 

### ISSUE THREAD

**Issue by gedger** [BottlecapDave/HomeAssistant-OctopusEnergy#953]
### Describe the feature

The "current demand sensor" sourced from the Home Pro is updated every 10 seconds and includes the state data that we want but also the attribute data ( Last evaluated, Data last retrieved) that we don't and seems more for debug use and not necessary. Doing the analysis of my database this one sensor is consuming 10% of the database and is some 3 times larger than same data sourced from the  Hildebrand Glow CAD due solely to the attributes.

I've noticed that the integration in general stores a lot of data in the database to the point where this one integration was doubling my database size. I've since Blacklisted all sensors from being recorded to solve this.

So a general request is can the use of the database be analysed to ensure that all the data including attributes are actually needed and not just a nice to have. Also use the debug feature to turn on attributes that are only needed when debugging.

Specifically can the Last evaluated, Data last retrieved attributes be removed from the current demand sensors.

### Expected behaviour

Only store the absolutely necessary data in the database. For instance Home Assistant keeps a last updated value for every sensor so replication is unnecessary.

### Use Case

Only store the state data for any sensor that is updated in sub minute timescales.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello.

> includes the state data that we want but also the attribute data ( Last evaluated, Data last retrieved) that we don't and seems more for debug use and not necessary

This is the main reason for it being here as it's useful when people are having issues with their sensors. I wanted attributes to be consistent between sensors where possible. More and more people are using HA from a non-technical background and so I don't want to expect them to dive in logs for details, nor increase the amount of raised issues if this data can be surfaced. I couldn't tell you if people use it from a database POV, but you're probably correct in your assumption.

> Doing the analysis of my database this one sensor is consuming 10% of the database and is some 3 times larger than same data sourced from the Hildebrand Glow CAD due solely to the attributes. 

I would be interested in knowing how you've come to your workings so I can keep an eye on it myself.

> I've noticed that the integration in general stores a lot of data in the database to the point where this one integration was doubling my database size.

There are a lot of sensors with a lot of data that update fairly frequently, so this to a point is to be expected.

> So a general request is can the use of the database be analysed to ensure that all the data including attributes are actually needed and not just a nice to have.

All attributes have been included because they've been requested or are needed in some form. Whether they need to be stored in the database is a different question, and one that I can't really answer as I don't have the data available as to what people do with the data. Some people put various bits of data into other sources (e.g. grafana), but again I can't say what bits of data people use in this capacity.

> Also use the debug feature to turn on attributes that are only needed when debugging.

The debug feature doesn't have this functionality. It merely changes log levels for the integration. This is HA functionality.

> Specifically can the Last evaluated, Data last retrieved attributes be removed from the current demand sensors...For instance Home Assistant keeps a last updated value for every sensor so replication is unnecessary.

I've done a light evaluation on the attributes and the following should occur in the next release.
* `last_evaluated` will be removed completely from all sensors. This was on my list once I found a way to expose the `last_updated` value, but I never got around to it (waiting for other breaking changes in part)
* `data_last_retrieved`, `mpan`, `mprn`, `serial_number`, `is_export`, `is_smart_meter` and
`target_times_last_evaluated` will be excluded from being recorded in the database due to their nature of either never changing or changing too frequently. They will still appear as attributes for debugging and automation purposes.

> Only store the state data for any sensor that is updated in sub minute timescales.

The data is stored whenever it is updated and this is dictated by HA sensors.

**Comment by gedger** [comment]
Thank you for responding. I take a copy of the database and then run this SQL. It provides a useful indiction of how the state table is being used. You can see that the smets2_consumption_now sourced from the Hildebrand device compared to the top entry of the same data from your integration. I don't quite understand at the moment why the counts are so different as it is exactly the same data sourced directly from the meter....

```
SELECT
  COUNT(state_id) AS cnt,
  COUNT(state_id) * 100 / (
    SELECT
      COUNT(state_id)
    FROM
      states
  ) AS cnt_pct,
  SUM(
    LENGTH(state_attributes.shared_attrs)
  ) AS bytes,
  SUM(
    LENGTH(state_attributes.shared_attrs)
  ) * 100 / (
    SELECT
      SUM(
        LENGTH(state_attributes.shared_attrs)
      )
    FROM
      states
      JOIN state_attributes ON states.attributes_id = state_attributes.attributes_id
  ) AS bytes_pct,
  states_meta.entity_id
FROM
  states
LEFT JOIN state_attributes ON states.attributes_id = state_attributes.attributes_id
LEFT JOIN states_meta ON states.metadata_id = states_meta.metadata_id
GROUP BY
  states.metadata_id, states_meta.entity_id
ORDER BY
  cnt DESC;
```

<img width="487" alt="Screenshot 2024-07-24 at 08 56 48" src="https://github.com/user-attachments/assets/90901c88-0bc0-4f27-87d2-44c118d25987">

**Comment by BottlecapDave** [comment]
`last_evaluated` has been removed and `data_last_retrieved` and `target_times_last_evaluated` have been excluded from the database as part of v12.0.0.

I am still including `mpan`, `mprn`, `serial_number`, `is_export` and  `is_smart_meter` unlike previously mentioned until I get some more feedback on how this data is being used from https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/discussions/957.

I'll keep this issue open until I have more time/feedback to evaluate other attributes.

**Comment by gedger** [comment]
A sensible way forward. Can I suggest that if this data is required you perhaps consider moving them into separate sensors?  I understand that if the sensor state changes then the updated state is stored together with all its attributes even if the attributes haven't changed value, a quirk of the HA data model. The upside of this modification is that the none changing attributes (now sensors in their own right) can be stored in the database with almost zero overhead as they rarely change, the downside is a more confusing data structure...

**Comment by BottlecapDave** [comment]
I have moved data out into separate sensors in the past where it's felt appropriate. There are potentially still areas where this could be improved (e.g. min/max/average rates for the current rate). However, a lot of the data that are in the attributes are there to provide a richer context to the sensors and give context and meaning for why the value might be why it is. Some of the attributes are calculated at the same time the state is calculated, which means that moving them to separate sensors would potentially result in duplicate processing and dependent on timing on when those sensor states get triggered could result in different results. There is also size limitations on what can be stored within the state of a sensor which would need to be taken into consideration (e.g. consumption breakdowns would be too big to store in the state). Then there is the additional overhead of managing the additional entities - There's already over 50 unique entities.

If people don't use the data stored within the database, or the data becomes irrelevant once not in the moment, then the data can be omitted from being saved (as has been done with `data_last_retrieved`), but still be available via the current ways.

**Comment by BottlecapDave** [comment]
The data_last_retrieved attributes have now been pulled out of the sensors and are their own sensors as part of [v13.0.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.0.0). This is because while the above fixes reduced the attribute table, it was still causing the state table to populate more than it should.
