### ISSUE TITLE
Factor in Solar Forecast for Daytime Target Rates in Agile.

### ISSUE THREAD

**Issue by Daverover66** [BottlecapDave/HomeAssistant-OctopusEnergy#960]
### Describe the feature

Incorporate forecast solar production into daytime (say between 10am and 4pm) target rate sensors for Agile, so half hour slots are selected based on both forecast solar production (from Solcast for example) and the cheapest Agile slots.

### Expected behaviour

Selected daytime target rate sensors are generated based on forecast solar production and cheapest Agile slots.

### Use Case

We have a dumb Rolec EV Chargepoint so are unable to vary the charging current with solar production.  Agile rates are becoming more frequently cheapest in mid-afternoon, so we often charge our car's battery during the day when the sun is shining. It would be useful to have an idea of whether or not there is a match between the peak solar production periods and the cheapest daytime Agile slots.  That way, we can maximise the use of our own solar to charge the EV battery, while avoiding paying too much should we get localised cloud cover and find ourselves drawing more from the grid.   

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello and sorry for not responding sooner.

I'm trying to avoid direct integrations with other solutions as it's a bit of a slippery slope as other solar forecast integrations are available and I don't want to spend time chasing integrating with various integrations.

I'm also not sure what the weighting would be like (e.g. if you have one hour of 1kwh predicted with 0.13p import and the next hour of 1.01kwh predicted with 0.14p import do you favour the higher cost because the kwh is slightly more?).

I feel like if this was provided it would be more generic and provide the ability to apply a weighting to the corresponding rates based on time rather than the selected target slot like is available now. 

For example, apply a weighting of 1.1 between 10:00-10:30; apply a weighting of 1.2 between 10:30-11:00, etc.

This would then mean people could integrate other data more easily (e.g. something other than solar) without the integration being tied to any particular integration. It also means that people could determine how the weighting is applied for themselves (is it a weighting of 1 for every kwh or 2 or something else).

**Comment by HACS-bank** [comment]
Take a look at EMHASS. That group are treating this as a more general optimisation challenge and solving it more generally.

**Comment by BottlecapDave** [comment]
The ability to add weightings to rates from external sources is now available in [v13.4.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.4.0). A [new service](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/services/#octopus_energyregister_rate_weightings) is now available, which allows you to apply weightings to rates, which are taken into account when calculating target rates and rolling target rates.
